### PR TITLE
Check null in LOAD_SOURCE_TABLES read

### PR DESCRIPTION
**Pull request by usadamasa**
I got NullPointerException in this line. 

```
java.lang.NullPointerException
com.google.cloud.solutions.datalineage.extractor.LoadJobExtractor.extractSources(LoadJobExtractor.java:61)
com.google.cloud.solutions.datalineage.extractor.LoadJobExtractor.extract(LoadJobExtractor.java:55)
com.google.cloud.solutions.datalineage.extractor.InsertJobTableLineageExtractor.extract(InsertJobTableLineageExtractor.java:58)
com.google.cloud.solutions.datalineage.transform.LineageExtractionTransform$IdentifyAndExtract.extract(LineageExtractionTransform.java:84)
```

### CODE REVIEW

**Comment by usadamasa** [comment]
@googlebot I signed it!

**Comment by anantdamle** [comment]
Thanks for the PR, 
Quick check for me to understand the fix.
1. Are you using a fully qualified table name in the query? (e.g. `projectId.datasetId.TableName`)
2. Does the table exists in the BigQuery?
3. Does the runner have permissions for BigQuery API?

**Comment by anantdamle** [comment]
@usadamasa The fix while meaningful will require matching Unit-Test case(s) to show-case when that value can be null? and how handling the null case is useful.

**Comment by usadamasa** [comment]
@anantdamle 
Sorry for my late reply.
I tried to reproduce it in my environment, but it did not occur and I did not know the reproduction condition.
It is possible to write such a test case, but there is no guarantee that it will meet the actual conditions.

**Comment by anantdamle** [comment]
no problem. 
Using Cloud Logging you can go back to the logs from the failed job and extract the request proto/JSON.
Can you try that?

**Comment by anantdamle** [comment]
@usadamasa do you have any updates?

**Comment by anantdamle** [comment]
@usadamasa in the absence of any activity from your end for the last 30 days, I'm sorry to close his PR.  In case the changes seem important later, request you to kindly reopen with updated Unit-tests.

**Pull request closed without merging**
